;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-force-normal-state
        evil-forward-char
        evil-next-line
        evil-previous-line
        org-self-insert-command
        ruby-electric-curlies
        ruby-electric-matching-char
        ))

(setq mc/cmds-to-run-once
      '(
        ensime-mouse-motion
        evil-backward-char
        evil-normal-state
        mac-mwheel-scroll
        ruby-electric-space
        ))
