;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-delete
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-previous-line
        org-self-insert-command
        ruby-electric-curlies
        ruby-electric-matching-char
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        ensime-mouse-motion
        evil-backward-char
        evil-backward-word-begin
        evil-normal-state
        find-user-init-file
        mac-mwheel-scroll
        ruby-electric-space
        smex
        sp--self-insert-command
        sp-kill-hybrid-sexp
        text-scale-decrease
        text-scale-increase
        ))
